import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Providers } from '@/components/theme/providers'
import ThemeSwitch from '@/components/theme/switch'
import { auth } from '@/utils/auth'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  if (!session?.user) {
    return (
      <html>
        <body>
          <div>Not logged in</div>
        </body>
      </html>
    )
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="absolute right-0 top-0">
            <ThemeSwitch />
          </div>

          <header>{session?.user.email}</header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
